version: "3"

services:
  api:
    build: ./api
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      PASSWORD_HASHED_KEY: ${PASSWORD_HASHED_KEY}
      JWT_SECRET: ${JWT_SECRET}
      FRONT_END_URL: "http://127.0.0.1:3000"
    volumes:
      - "account-book.api:/repo"
      - "account-book.api.go.1.11:/go"
    ports:
      - "8080:8080"
    tty: true
  web:
    build: ./web
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      REACT_APP_DEV_API_URL: "http://127.0.0.1:8080"
    volumes:
      - "account-book.web:/repo"
    ports:
      - "3000:3000"
    tty: true
volumes:
  account-book.api:
  account-book.api.go.1.11:
  account-book.web:
