version: "3"

services:
  api:
    build: ./api
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      FRONT_END_URL: "https://127.0.0.1:3000"
    volumes:
      - "account-book.api:/account-book.api"
      - "account-book.api.go:/go"
    ports:
      - 127.0.0.1:8080:8080
    tty: true
  web:
    build: ./web
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      REACT_APP_DEV_API_URL: "https://127.0.0.1:8080"
    volumes:
      - "account-book.web:/account-book.web"
    ports:
      - 127.0.0.1:3000:3000
    tty: true
volumes:
  account-book.api:
  account-book.api.go:
  account-book.web:
